#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely
# and responds to SIGTERM with "I am invincible!!!"

# Trap the SIGTERM signal (signal 15)
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
